apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvp
  namespace: default    
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: rsvp
  template:
    metadata:
      labels:
        app: rsvp
    spec:
      containers:
      - name: rsvp-app
        image: teamcloudyuga/rsvpapp
        env:
        - name: MONGODB_HOST
          value: "4.7.147.112"  # Replace with your MongoDB VM's IP
        - name: LINK
          value: "http://www.cloudyuga.guru"
        - name: TEXT1
          value: "My K3s Setup"
        - name: TEXT2
          value: "RSVP Application"
        - name: COMPANY
          value: "Hewlett Packard Enterprise"
        ports:
        - containerPort: 5000
          name: web-port