apiVersion: v1
kind: Service
metadata:
  name: rsvp
  namespace: default  
  labels:
    apps: rsvp
spec:
  type: NodePort
  ports:
  - name: web-port
    nodePort: 30080
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: rsvp